require('sets')
require('remaps')
require('pluginstalls')
require('autocommands')

-- Plugins (those that need configuration!!!
require('plugconfigs.gruvbox')
-- require('plugconfigs.catppuccin')
require('plugconfigs.lualine')
require('plugconfigs.treesitter')
require('plugconfigs.lsp')
require('plugconfigs.nvimgo')
require('plugconfigs.fidget')
require('plugconfigs.telescope')
require('plugconfigs.autocompletion')
require('plugconfigs.tabline')
require('plugconfigs.gitsigns')
require('plugconfigs.comments')
require('plugconfigs.daptext')
require('plugconfigs.telescope-fb')
require('plugconfigs.fold')
require('plugconfigs.lint')
require('plugconfigs.ts-context')
require('plugconfigs.lspsaga')
require('plugconfigs.notify')
require('plugconfigs.dap')
